import 'package:flutter/material.dart';

class Terms extends StatefulWidget {
  @override
  _State createState() => new _State();
}

class _State extends State<Terms> {


  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Terms & Conditions'),
      ),
      body: ListView(
        children: [
          Column(
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.start,

            children: <Widget>[
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('TERMS OF SERVICE',
                      style: TextStyle(
                          color: Colors.red,
                          fontWeight: FontWeight.bold,
                          fontSize: 20),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('In terms of Information Technology statutes, this document is an electronic record. Being generated by a computer system it does not require any physical or digital signatures.'),
                  ],
                ),
              ),

              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('1. This document is published in accordance with the provisions of Information Technology regulations that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of:',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('(a) You must read, agree with and accept all of the terms and conditions contained in this Agreement in order to use our Website located at www.airobotica.in (the "Website") and related software and services (collectively with the Site, the "AIRobotica Platform")'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('(b) The Website www.Airobotica.in (hereinafter referred to as "Airobotica”), owned by AIRobotica Services Private Limited where such expression shall, unless repugnant to the context thereof, be deemed to include its respective legal heirs, representatives, administrators, permitted successors and assigns;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('(c) By using the Website, You accept and agree to be bound by this Agreement, the Privacy Policy, as well as rules, guidelines, policies, terms and conditions applicable to any service that is provided by this Website, that shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. Your use of this Website is evidence that you have read and agreed to be contractually bound by these Terms of Service and our Privacy Policy. Please read both carefully. The use of this Website by You is governed by this policy and any policy so mentioned by terms of reference. If you do not agree with any of these terms, please discontinue using the Website.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('(d) We hold the sole right to modify the Terms of Service without prior permission from You or providing notice to You. The relationship creates on You a duty to periodically check the Terms of Service and stay updated on its requirements. If You continue to use the Website or avail any of its services without registration following such change, this is deemed as consent by You to the so amended policies. Your continued use of the Website is conditioned upon your compliance with the Terms of Service, including but not limited to compliance with the Terms of Service even after alterations, if any'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('2. DEFINITIONS',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),

              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('a. "We", "Us", "Our", “Airobotica Platform” shall mean Airobotica the Website/the portal or the Company . b. “Agreement” shall mean and refer to this Terms of Service, including any amendments that may be incorporated into it. c. "You" or "User" shall mean any natural or legal person who has agreed to become a user of the Airobotica Platform by signing up to the Website. The Airobotica Platform also provides certain services without registration/acceptance, and such provision of services does not absolve You of this contractual relationship. This shall also include Organisers. d. "Customer" shall mean any User who shall utilize the Airobotica Platform to request for Services to be performed by any Organiser. From time to time, Airobotica may act as a Customer, and the terms and conditions of this Agreement applicable to Customers will apply to Airobotica when acting in this way. e. "Organiser" means any enterprise or individual User utilizing the Airobotica Platform to offer Services to Customers. f. "Contract" means a particular project or set of ongoing tasks for which a Customer has requested Services to be offered by a Organiser and the Organiser has offered on the Airobotica Platform. g. “Third Party” shall mean and refer to any individual(s), enterprise or entity apart from the Users and Airobotica. h. "Services" shall mean and refer to the services offered on the site including but not limited to recreational, sporting and leisure activities and communications related services. i. "Organiser Fees" means a fixed fee which will be set by the Organiser for which the customer can avail the services offered and this fee will be non-negotiable. j. The terms “Party’ & ‘Parties” shall respectively be used to refer to the User and the Company individually and collectively, as the context so requires. The headings of each section in this Agreement are only for the purpose of organising the various provisions under this Agreement in an orderly manner. These headings shall not be used by either party to interpret the provisions contained under them in any manner. Further, the headings have no legal or contractual value.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('3. ONLINE WEBSITE PLATFORM',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('Airobotica is an online platform where users can find services, which shall include, but are not limited to setting out their preferences in relation to the activities they wish to partake in and Customers can book these services or learn about these Services. The Website works on the model of listing of Organisers and enabling them to showcase their profile. The Website also has a provision for the Users to provide their ratings and reviews on the quality of services. Airobotica is a portal where the Organisers, both agencies and freelancers will claim their own work. The Website shall take the amount as per the invoice of the event and after deducting a certain amount as commission shall give the remaining amount to the Organiser. The portal only brings together the Organisers and Customers. The Users of the Website are also allowed to post questions or queries regarding certain events on the Platform and these questions shall be visible to the Users of the Website in general and the responses to such questions/queries shall also be public.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('4. ELIGIBILITY',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('The User represents and warrants that he/she is competent and eligible to enter into legally binding agreements and that he/she has the requisite authority to bind himself/herself to these Terms, as determined solely by the provisions of the Indian Contract Act, 1872. The User may not use the Airobotica Platform if he/she is not competent to contract under the Indian Contract Act, 1872, or is disqualified from doing so by any other applicable law, rule or regulation currently in force.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('5. CONTENT',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('All information provided by Users are self-declared and not verified by Airobotica. Any and all information posted by any User including but not limited to their photographs, videos, company name, Airobotica has the right to use this Content for promotions or marketing purposes.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('Airobotica allows users to contribute different kinds of Content, including reviews, photos and videos. You alone are responsible for Your Content posted on the Website. The User’s contributions to the Website should be unbiased and objective. Airobotica does not and cannot review all communications or Content uploaded to the Site and is not responsible for the Content, quality, or consequences of your uploading such communications or Content. Notwithstanding the foregoing, Airobotica shall delete/ remove/ modify/ block the content/ reviews if, the reviewer attempts to use any improper/ indecent/ abusive language or tries to defame any Organiser for private/ personal/ professional reasons. A User shall not use the Website in any way that causes, or may be likely to cause damage or impairment to the Website or in any manner harms the Company or any other person or entity (as determined by the Company in its sole discretion) or interrupt free access to it in any way. A User shall not use the Website to host, display, upload, post, submit, distribute, modify, publish, transmit, update or share any Content that:'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(a) belongs to another person and to which you do not have any right;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('''(b) is grossly harmful, harassing, blasphemous defamatory obscene, pornographic, pedophilic, libelous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever;'''),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(c) harms minors in any way;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(d) infringes any patent, trademark, copyright or other proprietary rights;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(e) violates any law for the time being in force;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(f) deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(g) impersonates another person;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(h) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of the Website and/or the Services or any connected network or any computer resource, or otherwise interferes with any entity’s use or enjoyment of the Website and/or the Services; and'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(i) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insults any other nation;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(j) is posted for any fraudulent purpose. The User acknowledges and agrees that Airobotica may use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display any or all photographs, audio, video and text of Customer obtained through the Platform(s) to create marketing materials (collectively, "Content"), in whole or in part, in any manner or media as Airobotica sees fit. Content related to business photos and videos should be broadly relevant to the business and reflect the typical consumer experience (e.g., what the business looks like, what the business offers, etc.).If You post a photo or video that showcases a more unique personal experience with a business, We may remove it from the photo gallery for the business, but it still may appear alongside Your review if you write one about the business.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('Guidelines for uploading photos and videos: ',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• All User photos and videos should be broadly relevant to the Service and reflect the typical consumer experience (e.g, what the Service looks like, what the User offers, etc.).'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• If You post a photo or video that showcases a more unique personal experience with a business (e.g., your smiling group of friends at the bar, the fly in your soup), We may remove it from the photo gallery for the business, but it still may appear alongside Your review if You write one about the business.  '),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• Photos, Videos and depicting of imagery showing violence, drug use, nudity, near nudity, or suggestive acts shall not be uploaded. The Website shall delete any such Content.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text(' • Users shall not use their videos to disparage other businesses. Also Users shall not request or solicit reviews from other Users or respond to User reviews. Airobotica reserves the right to delete, remove, modify refuse to accept or edit any communication or Content that it may determine, in its sole discretion, violates or may violate this Agreement, the intellectual or proprietary rights of others, any of its policies or is otherwise unacceptable in its discretion, and you hereby agree to forfeit any fees payable in respect of such Content to Airobotica or as it may direct.'),
                  ],
                ),
              ),

              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('6. REGISTRATION ',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('To fully avail the services of the Website and use it, registration is required. Users can register on the Website either as Customers or as Organisers and can also register themselves using their Facebook account. The Organisers shall upload their team, work and Customer profile after registration. Airobotica shall approve the Users detailed profile after basic scrutiny of the Content and pictures. The Website, however, does not guarantee the authenticity of the claim of the work. The professionals seeking to provide reviews and ratings can do so only after their registration. One can register themselves on the Website by providing their username, email, password, first name and last name or may register using their social account.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('Notwithstanding the aforesaid, an individual can visit the Website however to avail such service proper registration is required. Membership of this Website is available only to those above the age of 18 years. barring those “Incompetent to Contract” which inter alia include insolvents. If You are a minor and wish to use the Website, You may do so through Your legal guardian and Airobotica reserves the right to terminate Your account on knowledge of You being a minor and having registered on the Website or availing any of its services.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('''All information provided by the User, Customers and Organiser must be true, accurate and complete. Airobotica reserves the right (but has no obligation) to verify any and all information provided on a User's profile. By registering on the Airobotica Platform, the User is attesting that he/she/it has the skills and ability to perform the requested Services by the deadline stated in the job posting or agreed upon.'''),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('The User is solely responsible for ensuring and maintaining the secrecy and security of his/her Airobotica account password. The User agrees not to disclose this password to any third party and shall be solely responsible for any use of or action taken through the use of such password on Airobotica.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('7. TERM',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('These Terms shall continue to form a valid and binding contract between the Parties, and shall continue to be in full force and effect until the User continues to access and use the Airobotica Platform. The Parties agree that certain portions of these Terms (“Sections”), such as Sections 15, 16, 17, 18, 19& 23, 24, 27 shall continue to remain in full force and effect indefinitely.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('8. TERMINATION',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text(' Airobotica reserves the right, in its sole discretion, to unilaterally terminate the User’s access to the products and services offered on the Airobotica Platform , or any portion thereof, at any time, without notice or cause. The User shall continue to be bound by these Terms, and it is expressly agreed to by the Parties that the User shall not have the right to terminate these Terms till the expiry of the same, as described in the Clause hereinabove.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('Either party may terminate the Agreement at any time, with or without cause, effective immediately upon written notice to the other party (or by terminating or suspending User’s account), provided, that any such termination for convenience shall not affect the validity of any agreements that have been executed prior to termination and this Agreement with Organisers shall continue to apply with respect to such agreements.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('9. COMMUNICATIONS ',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('By using the Airobotica Platform, it is deemed that You have consented to receiving telephonic calls, SMSs and/or emails from Airobotica at any time it deems fit. We, at Airobotica, shall reach out to communicate with you and enhance your experience while using the platform. We shall also inform you about the new services offered by us. Such communications shall be sent to You on the telephone number and/or email id provided by You for the use of the Airobotica Platform which are subject to our Privacy Policy. These communications include, but are not limited to contacting you through'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('information received from Third Parties. Such communications by Us is for purposes that inter alia include clarification calls, marketing calls and promotional calls. You may also be contacted by Organisers with whom we have entered into a contract in furtherance of our rights, duties and obligations under this document and other policies followed by Us and with whom you have become acquaintanices with from the Airobotica Platform. Such contact shall be made only in pursuance of such objectives and services and no other calls shall be made. In addition, You may also be contacted by Third Parties who may have access to the information disclosed by You or to whom We may have disclosed Your information for purposes such as, but not limited to statistical compilations.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('The sharing of the information provided by You shall be governed by our Privacy Policy.',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('10. PAYMENT TERMS AND CHARGES ',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('Each User understands and agrees that:'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• Airobotica shall charge commission. Moreover, Airobotica is not a party to the fee being finalised between Organisers and their Customers.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text(' • In the event of any dispute regarding the amounts held by Airobotica, We shall have the right (in addition to all other rights it may have) to deposit all funds held pursuant to this Agreement in the courts of Bangalore, Karnataka'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• All Fees paid to Airobotica are refundable for the services rendered which shall be governed by the refund policy at https://www.airobotica.in/assets/files/Cancellation_and_Refund__Airobotica3.docx.pdf. '),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• We reserve the right to amend the fee policy and charge for all the servies which the Airobotica Platform offers. In the event of such change in policy, Users shall be intimated of the same via email/telephone and such change shall be effective as soon as Users have been intimated. Subsequent to such change, it is the choice of the User whether or not to continue with the services offered by Us.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('11. SECURITY',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('Transactions on the Airobotica Platform are secure and protected. Any information entered by the User when transacting on the Airobotica Platform is encrypted to protect the User against unintentional disclosure to third parties. The User’s credit and debit card information is not received, stored by or retained by the Platform in any manner. This information is supplied by the User directly to the relevant payment gateway which is authorized to handle the information provided, and is compliant with the regulations and requirements of various banks and institutions and payment franchisees that it is associated with.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('12. TAXES',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('The User takes full responsibility for payment of all taxes and fees that are levied or arise in the course of use of the Platform.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('13. USER’S OBLIGATIONS',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('The User undertakes to fulfil the following obligations. Failure to satisfy any of these obligations gives Us the right to permanently suspend Your account and/or claim damages for any losses that accrue to Us or additional costs that may be imposed on us.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('➢ You hereby certify that you are at least 18 years of age.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('➢ You hereby agree to provide genuine credentials during the process of registration for the Platform. You shall not use a fictitious indentity to register.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('➢ You agree that any Content posted by shall be unbaised and objective. You must also ensure that your contributions to the Website are relevant and appropriate to the Website. You alone are responsible for Your Content.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('➢ You agree not to publicize other User’s private information without their consent. Such private information shall include but not be limited to close-up photos or videos, other User’s full names and address.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('➢ You agree to ensure the email address and mobile number provided in your account registration is valid at all times and shall keep your contact information accurate and up-todate.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('➢ You agree that you are solely responsible for maintaining the confidentiality of your account password. You agree to notify us immediately of any unauthorized use of your account. We reserve the right to close your account at any time for any or no reason.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('➢ You agree to comply with all local laws and regulations governing the downloading, installation and/or use of the the Airobotica Platform, including, without limitation to, any usage rules set forth in this Agreement.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('➢ You agree that all Service Contracts between any Customer and Organiser shall name Airobotica as an express third party beneficiary under the Service Contract (but not as a party to that agreement).'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('''➢ You agree to make no representations or warranties or enter into any contracts on behalf of Airobotica. Customer and Organiser may agree to additional terms in their Service Contract materially different than the standard terms; however, nothing in such Service Contract will in any way limit or modify Airobotica's rights.'''),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('➢ You recognize, acknowledge and agree that You are not an employee of Airobotica and that Airobotica does not, in any way, supervise, direct, or control Your work or Services. However the employees of Airobotica can also be Users;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('➢ You undertake not to: • Cut, copy, distribute, modify, recreate, reverse engineer, distribute, disseminate, post, publish or create derivative works from, transfer, or sell any information or software obtained from the Airobotica Platform. For the removal of doubt, it is clarified that unlimited or wholesale reproduction, copying of the Content for commercial or noncommercial purposes and unwarranted modification of data and information within the Content of the Website is not permitted. Should You want to engage in one or more such actions, prior permission from Airobotica must be obtained;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• Access (or attempt to access) the Airobotica Platform and/or the materials or Services by any means other than through the interface that is provided by the Airobotica Platform. The use of deep-link, robot, spider or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Airobotica Platform or Content, or in any way reproduce or circumvent the navigational structure or presentation of the Airobotica Platform, materials or any Content, to obtain or attempt to obtain any materials, documents or information through any means not specifically made available through the Airobotica Platform is prohibited.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('You acknowledge and agree that by accessing or using the Platform, You may be exposed to Content from other Users or Third Parties that You may consider offensive, indecent or otherwise objectionable. We disclaim all liabilities arising in relation to such offensive Content on the Platform. Further, You may report such offensive Content;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('''• Use the Airobotica Platform in any manner that may impair, overburden, damage, disable or otherwise compromise (i) Company’s services; (ii) any other party's use and enjoyment of the Company’s services; or (iii) the services and products of any Third Party (including, without limitation to, the Authorized Device);'''),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• use the Services or Materials for any unlawful purposes or to conduct any unlawful activity, including, but not limited to, fraud, embezzlement, money laundering or identity theft;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• abuse, harass, threaten, defame, disillusion, erode, abrogate, demean or otherwise violate the legal rights of others; • engage in any activity that interferes with or disrupts access to the Airobotica Platform or the Services (or the servers and networks which are connected to the Website);'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• upload or distribute files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of the Airobotica Platform;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• Download any file posted in the Airobotica Platform that you know, or reasonably should know, cannot be legally distributed in such manner;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• Probe, scan or test the vulnerability of the Airobotica Platform or any network, devises and software solutions to the Airobotica Platform, nor breach the security or authentication measures on the Airobotica Platform or any network, devises and software solutions connected to the Airobotica Platform. You may not reverse lookup, trace or seek to trace any information on any other user, of or visitor to, the Airobotica Platform, or exploit the Airobotica Platform or Service or information made available or offered by or through the Airobotica Platform, in any way whether or not the purpose is to reveal any information, including but not limited to personal identification information, other than Your own information, as provided for by the Airobotica Platform;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• Disrupt or interfere with the security of, or otherwise cause harm to, the Airobotica Platform, systems resources, servers, software solutions or networks connected to or accessible through the Airobotica Platform or any affiliated or linked Websites;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• Use the Airobotica Platform or any material or Content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of this Website or other Third Parties;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• Violate any applicable laws or regulations for the time being in force within or outside your home country;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• Violate any code of conduct or other guidelines, which may be applicable for or to any particular Service;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• Threaten the unity, integrity, defence, security or sovereignty of your home country, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• disseminate information through the Airobotica platform that is false, inaccurate or misleading or violate any applicable laws or regulations for the time being in force in or outside your home country.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('➢ Customers agree to respond promptly to communications with and requests for information from the Organiser.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('➢ The Organiser is responsible for providing all tools and resources necessary to complete the Contract, unless explicitly stated in advance by the Customer. Organisers agree to respond to all Customer communications and requests for information within one business day. If the Organiser will be unable to meet this requirement due to an absence, he is expected to notify the Customer at least 2 weeks prior. After the completion of a Contract, the Organiser can provide timely, honest and objective feedback on the Customer. 14 CONFIDENTIAL INFORMATION Confidential Information shall mean any information disclosed by the Customer on the Platform, related to the project. However, Confidential Information shall not include information that:'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(a) is now or subsequently becomes publicly known through no wrongful act or omission of the Organisers or anyone to whom it discloses such information;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(b) the Organisers can demonstrate by its written records to have had rightfully in the Customers possession, free of restriction, prior to the date of this Agreement;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(c) the Organisers can demonstrate by its written records to have obtained on or after the date of this Agreement, rightfully and free of restriction, from a third party who has the right to transfer or disclose it, provided that it was not acquired, directly or indirectly, from the Customer;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(d) the Organisers can demonstrate by its written records to have been independently developed. All Organisers using the Airobotica Platform acknowledge that certain information disclosed by Customer may be confidential and, if so, must be protected. All Confidential Information and its embodiments and derivatives shall remain the sole and exclusive property of the Customer and no license or other right with respect to Confidential Information is granted or implied hereby.'),
                  ],
                ),
              ),

              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('15. REPRESENTATIONS AND DISCLAIMER OF WARRANTIES',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),

              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('a) Except as otherwise expressly stated on the Website, all Services offered on the Website are offered on an "as is" basis without any warranty whatsoever, either express or implied.'),
                  ],
                ),
              ),

              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('b) All commercial/contractual terms are offered by and agreed to between User and Organisers alone. Airobotica disclaims all liability to either the Customer or the Organiser or any person claiming for any breach of the terms of the Agreement based on the ratings, reviews or the work profile of Organisers mentioned on Airobotica portal.'),
                  ],
                ),
              ),

              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('c) The Company/Website makes no representations as to the reliability, capability, or qualifications of any Organiser or the quality, security or legality of any Services and Airobotica disclaims any and all liability relating thereto. The Company/Website does not implicitly or explicitly support or endorse the procurement of any Service on the Website.'),
                  ],
                ),
              ),

              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('d) The User agrees and undertakes that he/she is accessing the Website and transacting at his/her sole risk and that he/she is using his/her best and prudent judgment before availing any Services listed on the Website, or accessing/using any information displayed thereon.'),
                  ],
                ),
              ),

              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('e) The Website and the Company accepts no liability for any errors or omissions, whether on behalf of itself, any Organisers or third parties, or for any damage caused to the User, the User’s belongings, or any third party, resulting from the use or misuse of any Product purchased or service availed of by the User from the Website.'),
                  ],
                ),
              ),

              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('f) The Company/Website does not guarantee that the functions and services contained in the Website will be uninterrupted or error-free, or that the Website or its server will be free of viruses or other harmful components, and the User hereby expressly accepts any and all associated risks involved with the User’s use of the Website.'),
                  ],
                ),
              ),

              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('g) It is further agreed to by the Parties that the Contents of this Section shall survive even after the termination or expiry of the Terms and/or Policy.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('16. LIMITATION OF LIABILITY',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('g) It is further agreed to by the Parties that the Contents of this Section shall survive even after the termination or expiry of the Terms and/or Policy.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('g) It is further agreed to by the Parties that the Contents of this Section shall survive even after the termination or expiry of the Terms and/or Policy.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('17. INTELLECTUAL PROPERTY RIGHTS',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(a) All information, Content, services and software displayed on, transmitted through, or used in connection with the Airobotica Platform, including for example news articles, reviews, directories, guides, text, photographs, images, illustrations, audio clips, video, html, source and object code, trademarks, logos, and the like (collectively and hereinafter referred to as the "Content"), as well as its selection and arrangement, is owned by Us. You may use the Content only through the Airobotica Platform, and solely for your personal, non-commercial use.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('''(b) You may not, republish any portion of the Content on any Internet, Intranet or extranet site or incorporate the Content in any database, compilation, archive or cache. You may not distribute any Content to others, whether or not for payment or other consideration, and you may not modify, copy, frame, cache, reproduce, sell, publish, transmit, display or otherwise use any portion of the Content. You may not scrape or otherwise copy our Content without permission. You agree not to decompile, reverse engineer or disassemble any software or other products or processes accessible through the Airobotica Platform, not to insert any code or product or manipulate the Content of the Airobotica Platform in any way that affects the user's experience, and not to use any data mining, data gathering or extraction method.'''),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('18. INTELLECTUAL PROPERTY COMPLAINTS',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(a) We respect the intellectual property of others. If You believe Your work has been copied in a way that constitutes infringement or are aware of any infringing material on the Airobotica Platform, please email us at support@airobotica.in'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(b) By providing information to, communicating with, and/or placing material on, the Airobotica Platform, including for example but not limited to, communication during any registration and communication on the bulletin board, message or chat area, You represent and warrant:'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• You own or otherwise have all necessary rights to the Content you provide and the rights to use it as provided in this Terms of Service;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• all information You provide is true, accurate, current and complete, and does not violate these Terms of Service; and,'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('• the information and Content shall not cause injury to any person or entity. Using a name other than your own legal name is prohibited (except in those specific areas of the Airobotica Platform that specifically ask for unique, fictitious names such as, inter alia certain message boards and chat rooms). For all such information and material, you grant us, a royalty-free, perpetual, irrevocable, nonexclusive right and license to use, copy, modify, display, archive, store, distribute, reproduce and create derivative'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('works from such information, in any form, media, software or technology of any kind now existing or developed in the future. Without limiting the generality of the previous sentence, you authorize us to share the information across all our affiliated Websites, to include the information in a searchable format accessible by users of Airobotica Platform and other affiliated Websites, and to use your name and any other information in connection with its use of the material you provide. You also grant the right to use any material, information, ideas, concepts, know-how or techniques contained in any communication you send to us for any purpose whatsoever, including but not limited to developing, manufacturing and marketing products using such information. All rights in this paragraph are granted without the need for additional compensation of any sort to you.'),
                  ],
                ),
              ),


              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('19. GEOGRAPHICAL EXTENT',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(a) We make no representation that materials or Content available through our Airobotica Platform is appropriate or available for use in all countries worldwide.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(b) If You access or use the Airobotica Platform from a country or location where it is not appropriate or available, You are solely responsible for compliance with necessary laws and regulations for use of the Airobotica Platform.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('20. AMENDMENT',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(a) We may modify, replace, refuse access to, suspend or discontinue the Services, partially or entirely, or add, change and modify prices for all or part of the Services for You or for all Users at any time and in Our sole discretion. These changes shall become effective upon providing a notice of the same to You via email/ the home screen of the Website. We further reserve the right to withhold, remove and or discard any Content available as part of Your account, with or without notice, if deemed by Us to be contrary to this Agreement.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(b) Airobotica has no obligation to provide You with a copy of the information You or any other User provides on the Airobotica Platform or that the Airobotica Platform has accessed.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(c) Further, We reserve the right, in Our sole discretion, to modify or replace any part of this Agreement at any time, effective upon the date of giving Users notice of the same. Notice shall be provided of such change via email to the Users and/ or by posting a notice on the home screen of the Airobotica Platform. You and We both understand that there may be instances of difficulty in accessing or receiving email communication. We are not responsible if any email notice gets caught by Your SPAM folder, or if You do not see the email, or if You have given us an incorrect email id or if for any other reason You do not receive the email notice. Therefore, we encourage you to frequently open the Airobotica Platform to'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('monitor any changes. Your continued use of or access to the Services following the posting of any changes to this Agreement constitutes acceptance of those changes. We may also, in the future, offer new services and/ or features through the Airobotica Platform. Such new features and/ or services shall be subject to the terms and conditions of this Agreement.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('21. INDEMNIFICATION',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text(''' You agree to indemnify and hold harmless the Company, its independent Organisers, Organisers and consultants, and their respective directors, officers, employees and agents (collectively, "Airobotica Parties"), from and against any claims, damages, costs, liabilities and expenses (including, but not limited to, reasonable attorneys' fees) arising out of or related to'''),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(a) your access to or use of the Platform(s);'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(b) any Discussions or Messages you provide;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(c) your violation of these Terms and Conditions;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(d) your violation of any rights of another; (e) your conduct in connection with the platform(s); or'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('''(f) any products or services purchased or obtained by you in connection with the platform(s). You agree to fully cooperate in indemnifying Us at Your expense. Each Customer shall indemnify, defend and hold harmless the Indemnified Parties from any and all claims, damages, liabilities, costs, and expenses (including, but not limited to, reasonable attorneys' fees and all related costs and expenses) arising from or relating to:'''),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('''(i) such Customer’s use of Services, including without limitation claims by or on behalf of any Organiser for Worker's Compensation or unemployment benefits;'''),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(ii) any Service Contract entered into between such Customer and a Organiser; or'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('g) It is further agreed to by the Parties that the Contents of this Section shall survive even after the termination or expiry of the Terms and/or Policy.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('''(iii) any breach of their obligations set forth herein. Each Organiser shall indemnify, defend and hold harmless the Indemnified Parties from any and all claims, damages, liabilities, costs, and expenses (including, but not limited to, reasonable attorneys' fees and all related costs and expenses) arising from or relating to:'''),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('''(i) such Organiser's provision of Services.'''),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('''(ii) any Service Contract entered into between such Organiser and a Customer; or'''),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(iii) any breach of their obligations set forth herein;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(iv) alleged or actual breach of intellectual property by the Organiser of the rights of a third party;'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(v) misrepresentation, false or inaccurate data posted by the Organiser on the Website; or'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(vi) violation of applicable law by the Organiser.'),
                  ],
                ),
              ),

              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('22. DISPUTES ARISING OUT OF THIS AGREEMENT',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('All disputes involving but not limited to rights conferred, compensation, refunds, and other claims will be resolved through a two-step Alternate Dispute Resolution mechanism.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('14.1 Stage 1: Mediation. In case of a dispute, the matter will first be attempted to be resolved by a sole mediator who is a neutral third party and will be selected at the mutual acceptance of a proposed mediator by both parties. Both parties may raise a name for the sole mediator and in the case both parties accept the proposed name, the said person shall be appointed as sole mediator. In case the parties are not able to reach a consensus within two proposed mediators, the sole proprietorship reserves the right to decide who the final mediator is. The decision of the mediator is not binding on both parties.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('14.2 Stage 2: Arbitration. If the dispute is not settled by mediation, it shall be referred to and finally resolved by arbitration, which shall be governed by the law, rules and regulations of Bangalore, India. The Arbitral award is binding on both parties. The Arbitration Board shall comprise three members – one appointed by each party and the third member to be nominated by the two appointed members by mutual consent. Arbitration shall be held at Bangalore. The proceedings of arbitration shall be in the English language. The arbitrator’s award shall be final and binding on the Parties.The exclusive jurisdiction and venue for actions and disputes mentioned above shall be the courts located in Bengaluru, Karnataka, India and You hereby submit to the personal jurisdiction of such courts.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('23. PRIVACY:',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('We encourage you to read the Privacy Policy and to use the information it contains to make informed decisions regarding Your personal information. Please also note that certain information, statements, data and Content (such as but not limited to photographs) which You provide on the Airobotica Platform are likely to reveal Your gender, ethnic origin, nationality, age, and/or other personal information about You. You acknowledge and agree that your submission of such information is voluntary on Your part. Further, You acknowledge, consent and agree that we may access, preserve, and disclose information You provide to Us at any stage during Your use of the Airobotica Platform. Disclosures of information to Third Parties are further addressed in Our Privacy Policy.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('24. NOTICES:',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('Any and all communication relating to any dispute or grievance experienced by the User may be communicated to the Company by the User reducing the same to writing, and sending the same to the registered office of the Company by Registered Post, or send an email to support@airobotica.in'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('25. MISCELLANEOUS PROVISIONS:',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(a) Entire Agreement: The terms and conditions set forth in this Agreement and any additional or different terms expressly agreed by Customer and Organiser shall constitute the entire agreement and understanding of Customer and Organiser with respect to each Service Contract and shall cancel and supersede any other prior or contemporaneous discussions, agreements, representations, warranties, and/or other communications between them. Notwithstanding the foregoing, the Customer and Organiser shall always remain subject to the terms of the user Agreement.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('''(b) Waiver: The failure of either party at any time to require performance of any provision of this Agreement in no manner shall affect such party's right at a later time to enforce the same. No waiver by either party of any breach of this Agreement, whether by conduct or otherwise, in any one or more instances, shall be deemed to be, or construed as, a further or continuing waiver of any other such breach, or a waiver of any other breach of this Agreement.'''),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('(c) Severability: If any provision of this Agreement shall to any extent be held invalid, illegal or unenforceable, the validity, legality and enforceability of the remaining provisions of this Agreement shall in no way be affected or impaired thereby and each such provision of this Agreement shall be valid and enforceable to the fullest extent permitted by law. In such a case, this Agreement shall be reformed to the minimum extent necessary to correct any invalidity, illegality or unenforceability, while preserving to the maximum extent the rights and commercial expectations of the parties hereto, as expressed herein.'),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  children: <Widget>[
                    new Text('DISCLAIMER',style: TextStyle(color: Colors.grey[10],fontWeight: FontWeight.bold,
                        fontSize: 13),),
                  ],
                ),
              ),
              new Container(
                padding: new EdgeInsets.all(10.0),
                child: new Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text('The Airobotica Platform is merely a venue where Users may act as Customers or Organisers. Airobotica is not a party to any Service Contracts between Customers and Organisers. Airobotica shall not have any liability or obligations under or related to Service Contracts or any acts or omissions by Users. Airobotica has no control over Organisers or over the Services promised or rendered by Organisers. Airobotica makes no representations as to the reliability, capability, or qualifications of any Organiser or the quality, security or legality of any Services and Airobotica disclaims any and all liability relating'),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
